/* eslint-disable */
// Generated by scripts/generate-environment.mjs — do not edit by hand.
export const environment = {
  production: true,
  apiBaseUrl: "https://auditiq-api.onrender.com/api",
  wsBaseUrl: "wss://auditiq-api.onrender.com",
};
