/* eslint-disable */
// Generated by scripts/generate-environment.mjs — do not edit by hand.
export const environment = {
  production: true,
  apiBaseUrl: "https://grand-sawine-e82b5d.netlify.app/api",
  wsBaseUrl: "wss://grand-sawine-e82b5d.netlify.app",
};
