/* eslint-disable */
// Generated by scripts/generate-environment.mjs — do not edit by hand.
/** Values for non-production builds (imported from environment.ts). */
export const devEnvironment = {
  apiBaseUrl: "http://localhost:8000/api",
  wsBaseUrl: "ws://localhost:8000",
};
