/* eslint-disable */
// Generated by scripts/generate-environment.mjs — do not edit by hand.
export const environment = {
  production: true,
  apiBaseUrl: "https://auditiq-back.vercel.app/api",
  wsBaseUrl: "wss://auditiq-back.vercel.app",
};
